# This patch is required for roleArn. The pattern validation cannot be applied via Kubebuilder marker
# because of a bug in controller tools: https://github.com/kubernetes-sigs/controller-tools/issues/272
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: trainingjobs.sagemaker.aws.amazon.com
spec:
    validation:
        openAPIV3Schema:
            properties:
                spec:
                    properties:
                        roleArn:
                            pattern: '^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$'
